CREATE TABLE VILAO
(
    CODIGO     NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT 1),
    NOME       VARCHAR(50) NOT NULL,
    OUTRO_NOME VARCHAR(50),
    LEVEL      NUMBER(11),
    IMAGEM     VARCHAR,
    PODERES    VARCHAR,
    CONSTRAINT CODIGO_VILAO_PK PRIMARY KEY (CODIGO)
);